spring.application.name=LearningPlatform

# Oracle Autonomous Database
spring.datasource.url=jdbc:oracle:thin:@r0if5tcknf5eminu_high?TNS_ADMIN=/home/aandrewsv/oracle_wallet_app
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Boot Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Delegar 404 al GlobalExceptionHandler en lugar del BasicErrorController
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
